"""empty message

Revision ID: cca091187b78
Revises: 9431df2e9f45
Create Date: 2022-05-03 17:12:31.022832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca091187b78'
down_revision = '9431df2e9f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('points', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'points')
    # ### end Alembic commands ###
