version: "3.8"

services:
  db:
    container_name: mmap_db
    image: library/postgres:12.3
    ports:
      - "5520:5520"
    environment:
      - POSTGRES_DB=mmap
      - POSTGRES_USER=mmap
      - POSTGRES_PASSWORD=mmap
      - PGPORT=5520
