version: "3.8"

services:
  db:
    container_name: map_app_db
    image: library/postgres:12.3
    ports:
      - "5544:5544"
    environment:
      - POSTGRES_DB=map_app
      - POSTGRES_USER=map_app
      - POSTGRES_PASSWORD=map_app
      - PGPORT=5544
